in查询功能的实现
gotomicro/eorm pull request #102
Opened 2022-11-08 02:03 UTC by juniaoshaonian

2022-11-08 07:01 UTC, flycash commented on column.go
> +type Ins struct {
把 Ins 改成 values，私有的。

2022-11-08 07:02 UTC, flycash reviewed
- 在 .CHANGELOG 里面，把这个合并请求加进去;
- 看看 Github 的 action，修复一下 deepsource 之类的问题

2022-11-08 07:03 UTC, flycash commented
unused receiver 错误你只需要删掉那个 receiver 的名字就可以

2022-11-08 07:09 UTC, flycash commented
另外我有一个地方想要问问你的看法，就是某些时候使用 In 查询我们会遇到这么一个问题，就是我也不知道里面有没有元素。如果按照现在的逻辑，假如输入是空的话，那么生成的是：
```sql
SELECT * FROM XXX WHERE `id` IN ()
```
还有两种可以考虑的方向：
```
SELECT * FROM xxx WHERE true;
SELECT * FROM xxx WHERE false;
```
第一个意思是，如果要是 In 的候选元素不存在，就认为不需要这个查询条件，所以用 true。
第二个的意思是，如果In的元素没有，认为数据库根本筛选不出来任何结果，所以用 false。

2022-11-08 09:19 UTC, juniaoshaonian commented
> 另外我有一个地方想要问问你的看法，就是某些时候使用 In 查询我们会遇到这么一个问题，就是我也不知道里面有没有元素。如果按照现在的逻辑，假如输入是空的话，那么生成的是：
> 
> ```sql
> SELECT * FROM XXX WHERE `id` IN ()
> ```
> 
> 还有两种可以考虑的方向：
> 
> ```
> SELECT * FROM xxx WHERE true;
> SELECT * FROM xxx WHERE false;
> ```
> 
> 第一个意思是，如果要是 In 的候选元素不存在，就认为不需要这个查询条件，所以用 true。 第二个的意思是，如果In的元素没有，认为数据库根本筛选不出来任何结果，所以用 false。

我偏向于第二种，如果说是第一种并且后面没有其他条件的话就变成遍历全表了。表比较大的话会比较慢。

2022-11-08 09:33 UTC, juniaoshaonian commented on select_test.go
> +		},
传切片的时候，是作为一个整体还是说我们在内部帮他转化成 ... 的这种形式。

2022-11-09 06:13 UTC, flycash commented
> > 另外我有一个地方想要问问你的看法，就是某些时候使用 In 查询我们会遇到这么一个问题，就是我也不知道里面有没有元素。如果按照现在的逻辑，假如输入是空的话，那么生成的是：
> > ```sql
> > SELECT * FROM XXX WHERE `id` IN ()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还有两种可以考虑的方向：
> > ```
> > SELECT * FROM xxx WHERE true;
> > SELECT * FROM xxx WHERE false;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 第一个意思是，如果要是 In 的候选元素不存在，就认为不需要这个查询条件，所以用 true。 第二个的意思是，如果In的元素没有，认为数据库根本筛选不出来任何结果，所以用 false。
> 
> 我偏向于第二种，如果说是第一种并且后面没有其他条件的话就变成遍历全表了。表比较大的话会比较慢。

那可以，你修改一下代码，然后在In 和 NotIn 两个方法的注释里面说清楚，如果要是每元素的话，In 这个会被认为是 false。

2022-11-10 02:22 UTC, flycash requested changes

2022-11-10 02:22 UTC, flycash commented on column.go
> +	ins []any
ins 改名为 vals 或者 data 都可以。因为从目标上来说，它可能会被别的组件使用，所以使用 ins 不太适合

2022-11-10 02:22 UTC, flycash commented on predicate.go
> +	opFalse = op{symbol: "false", text: "false "}
text 都改成大写的 TRUE 和 FALSE

2022-11-10 02:22 UTC, flycash commented on predicate.go
> +	opFalse = op{symbol: "false", text: "false "}
预期结果是 WHERE FALSE OR xxx

2022-11-10 08:39 UTC, flycash commented on select_test.go
> +		{
这里还需要一个测试，就是传入了一个切片：
```go
var ids := []int{}
C("Id").In(ids...)
```
它也应该使用 FALSE。按照你的写法，应该是生成了 WHERE id IN()

2022-11-10 09:57 UTC, juniaoshaonian commented on select_test.go
> +		{
是的我修改一下

2022-11-15 02:50 UTC, flycash approved these changes

2022-11-15 02:51 UTC, merged