join查询
gotomicro/eorm pull request #122
Opened 2022-12-31 07:27 UTC by liangzai202204

2023-01-01 05:47 UTC, flycash requested changes
这边你漏了校验列：
- 在 SELECT XXX 部分校验列
- 在 WHERE 部分校验列
- 在 ON 部分校验列
也就是我出现在这几个地方的列，要么  table 本身有，要么 table.left 有，要么 join.right 有

2023-01-01 05:47 UTC, flycash commented on select.go
>  	if s.table != nil {
为什么在这里面还要 switch 呢？s.table 要么是 nil，要么不是 nil？不然你直接用一个 switch 也可以，也就是可以删掉外面的 if-else

2023-01-01 05:57 UTC, flycash requested changes
貌似你没有加单元测试和集成测试？单元测试要覆盖：
- 用 t.C 这种形态来指定列，并且用在 SELECT XXX, WHERE, ON 里面，包括聚合函数，也要测试指定非法列的情况
- JOIN 的情况，包括 left join, right join, join 和复合 join（就是 join 再和 join 一起）

2023-01-01 05:57 UTC, flycash commented
集成测试为join, left join 和 right 各写一个，然后用 t.C 来指定列。

2023-01-01 05:58 UTC, flycash requested changes
As 方法使用之后，在指定列的时候，生成的列名就带上了这个别名

2023-01-01 05:58 UTC, flycash commented on table.go
> +func (t Table) As(alias string) Table {
要测试这个方法

2023-01-04 06:25 UTC, flycash commented
rebase 过去最新的 gotomicro/eorm dev 分支上，我刚刚修复了一个 Github action 的问题。

2023-01-04 06:28 UTC, flycash requested changes

2023-01-04 06:28 UTC, flycash commented on select_test.go
> +		{
加两个测试用例：
- 使用 SELECT t1.xxx, t2.xxx 这种
- 使用 SELECT AVG(t1.xxx), AVG(t2.xxx) 这种

2023-01-04 06:28 UTC, flycash commented on select_test.go
> +		{
记得测试非法的情况

2023-01-04 06:28 UTC, flycash commented on select_test.go
> +				t3 := t1.RightJoin(t2).Using("UsingCol1", "UsingCol2")
Using 加一个 非法用例，就是你随便指定了一个列，而这个列并不是合法的列。

2023-01-05 16:01 UTC, liangzai202204 commented
集成测试\internal\integration\ select_test.go,TestMySQL8SelectJoin

2023-01-05 16:13 UTC, liangzai202204 commented
mysql初始化.\script\mysql\init.sql新增建表语句

2023-01-06 10:14 UTC, liangzai202204 commented on select_test.go
> +				t3 := t1.RightJoin(t2).Using("UsingCol1", "UsingCol2")
name: "join-using-cols-invalid",

2023-01-08 15:27 UTC, flycash requested changes

2023-01-08 15:27 UTC, flycash commented on internal/integration/select_test.go
> +	Op
文件漏提交了？

2023-01-08 15:27 UTC, flycash commented on internal/integration/select_test.go
> +	res = eorm.RawQuery[any](s.orm, "DELETE FROM `order_detail`").Exec(context.Background())
每一个 res 都检测 require.NoError(s.T(), res.Err())

2023-01-08 15:27 UTC, flycash commented on internal/integration/select_test.go
> +		{
其实在集成测试的时候，因为我们主要目标是放在检测和数据库交互上，所以类似这种在单测层面上就能检测的测试用例，就不用写的。以后的合并请求可以不用写，这个你可以删掉，也可以留着。

单元测试和集成测试的侧重点就不太一样。

2023-01-08 15:27 UTC, flycash commented on internal/integration/select_test.go
> +	res = eorm.RawQuery[any](s.orm, "DELETE FROM `order_detail`").Exec(context.Background())
检测每一个 res.Err，使用 require.NoErr

2023-01-08 15:27 UTC, flycash commented on internal/integration/select_test.go
> +	Orderres1 := eorm.NewInserter[test.Order](orm).Values(&test.Order{Id: 1, UsingCol1: "usingcoa1_1", UsingCol2: "usingcoa1_2"}).Exec(context.Background())
Inserter.Values 是支持批量插入的=。=你可以一次性传入所有的 test.Order。另外局部变量不要使用大写开头

2023-01-08 15:27 UTC, flycash commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
？ 这个地方，AllColumns 看起来不是返回 AllColumns ？你是为了支持类似 t1.* 这种用法吗？那么应该是：
```go
func (t Table) AllColumns()  {

}
```

2023-01-08 15:27 UTC, flycash commented on select.go
> +			s.writeByte(')')
丢过去一个单独的方法

2023-01-08 15:27 UTC, flycash commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
这个地方其实我是很犹豫的。
```go
func (t Table) AllColumns()  RawExpr {
    return Raw("t1.*")
}
```
或者
```go
func (t Table) AllColumns()  []Column {
    // 遍历 t 里面的所有字段
}
```

2023-01-08 15:27 UTC, flycash commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
这两种我都觉得可以。你有没有别的建议？对应的，buildAllColumns 那个地方就不需要改了。

2023-01-08 15:27 UTC, flycash commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
```go
// RawExpr
NewSelector().Select(t1.AllColumns())
// []Columns
NewSelector().Select(t2.AllColumns()...)
```

2023-01-08 15:27 UTC, flycash commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
这种做法比较无侵入

2023-01-08 15:27 UTC, flycash commented on select.go
> +			if expr.table != nil {
能不能把 Column 这个一整个抽取出来作为一个方法？ buildColumn(c Column)

2023-01-08 15:27 UTC, flycash commented on select.go
> +			//m, okay := s.meta.FieldMap[aggregate.alias]
这个确实不需要，所以你可以删掉

2023-01-09 09:06 UTC, liangzai202204 commented on .deepsource.toml
> -# Copyright 2021 gotomicro
这个是github系统代码检查删了，已补。。

2023-01-09 09:07 UTC, liangzai202204 commented on internal/integration/select_test.go
> +	Op
测试用，可忽略

2023-01-09 09:07 UTC, liangzai202204 commented on internal/integration/select_test.go
> +		{
暂时留着吧

2023-01-09 09:42 UTC, liangzai202204 commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
这里的AllColumns，是没有指定列时，如：
`NewSelector[Order](db).From(t3)`
默认生成：
`SELECT `order`.* FROM XXX`

2023-01-09 09:44 UTC, liangzai202204 commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
当然，也可以这样，指定了列
`// RawExpr
NewSelector().Select(t1.AllColumns())
// []Columns
NewSelector().Select(t2.AllColumns()...)`

2023-01-09 13:43 UTC, liangzai202204 commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
`NewSelector[Order](db).From(t3).Select(t1.AllColumns(), t2.AllColumns())`
这样t1和t2拿不到DB，获取不到方言

2023-01-09 13:59 UTC, liangzai202204 commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
比如这样，或者有其他建议？。。。
```go
func (t Table) AllColumns() RawExpr {
	if t.alias != "" {
		return Raw("`" + t.alias + "`.*")
	}
	// 硬塞一个core。。
	t.core = core{metaRegistry: model.NewMetaRegistry()}
	meta, err := t.metaRegistry.Get(t.entity)
	if err != nil {
		// 不好处理错误
		panic("eorm:Table 获取不到meta")
	}
	//t.quote(meta.TableName)
	//_, _ = t.buffer.WriteString("`" + meta.TableName + "`" + ".*")
	//t.pointStar()
	return Raw("`" + meta.TableName + "`.*")
}
```

2023-01-09 14:02 UTC, liangzai202204 commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
测试用例：
```go
{
			name: "join-using-cols-all",
			s: func() QueryBuilder {
				t1 := TableOf(&Order{}).As("t1")
				t2 := TableOf(&OrderDetail{})
				t3 := t1.Join(t2).Using("UsingCol1", "UsingCol2")
				return NewSelector[Order](db).From(t3).Select(t1.AllColumns(), t2.AllColumns())
			}(),
			wantQuery: &Query{
				SQL: "SELECT `t1`.*,`order_detail`.* FROM (`order` AS `t1` JOIN `order_detail` USING (`using_col1`,`using_col2`));",
			},
}
```

2023-01-10 03:09 UTC, flycash commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
其实 t1.AllColumns 不需要搞得那么复杂，我们直接要求用户指定表的别名，也就是只保留：
```go
func (t Table) AllColumns() RawExpr {
	return Raw("`" + t.alias + "`.*")
}
```
我们通过注释的手段告诉用户，这个地方需要别名。实际上我觉得站在实践的角度，也是 TableOf 设置别名最好。甚至于我还考虑过把 TableOf 修改为：
```go
func TableOf(entity any, alias string) 
```
你觉得呢？
这个地方不是很有必要惯着用户。

2023-01-10 03:14 UTC, flycash commented
- check license 失败，说明你有一些新文件没有加上我们的 license 说明
- format go code，记得调用 make check, 或者自己调用 goimports 来格式化代码
- changelog，就是把这个合并请求加进去我们的 .CHANGELOG 里面的 develop 下面
- deepsource，应该就是各种静态代码检查的问题，你需要进去看看。有些你觉得没必要修的，可以留言
- codecov，这个可能是统计不准，你 rebase 一下最新的 gotomicro/eorm 的 dev 分支。（rebase 各种冲突的话，你合并一下也可以）

2023-01-10 03:17 UTC, liangzai202204 commented on select.go
> +func (s *Selector[T]) AllColumns(table TableReference) error {
我觉这样比较好
```go
func TableOf(entity any, alias string)
```

2023-01-10 03:21 UTC, flycash reviewed
TableOf 强制要求指定别名，大体上我觉得还能接受，你觉得用户会不会觉得很麻烦？

2023-01-10 03:21 UTC, flycash commented on builder.go
> +	case nil:
这个分支就是完全没有调用 From 就会进来这里，你可以加一个测试用例覆盖了。

2023-01-10 03:21 UTC, flycash commented on select.go
> +		}
从这一段的逻辑来看，我们改成 TableOf(xx, "") 要求用户一定要指定别名，能够极大的简化我们内部的流程，也就是不需要考虑那么多

2023-01-10 03:31 UTC, liangzai202204 commented on builder.go
> +	case nil:
TableOf 强制要求指定别名，使用上倒没什么问题，就是用户有些情况不想用别名，这就不太友好。
不过目前的方案，用户也可以不调用t1.AllColumns

2023-01-10 16:20 UTC, flycash commented on builder.go
> +	case nil:
或者我们保持 TableOf 简单，不强制指定别名，但是如果用户要用 t1.AllColumns，就必须指定别名。我们可以在 AllColumns 这个方法上加上注释。

2023-01-10 16:20 UTC, flycash commented on builder.go
> +	case nil:
AllColumns 这个也不需要校验有没有别名，用户但凡看一眼注释就不会用错。即便用错，数据库也会返回错误。

2023-01-10 16:24 UTC, flycash commented on select.go
> +				meta, err := s.metaRegistry.Get(t.entity)
这里，如果 Table 本身没有别名，我们也不要用表明来作为别名，我更加希望用户养成指定 Table 的别名的良好习惯，因为这样可读性更高并且没有什么隐含的逻辑。

也就是，没有指定别名就使用表名来作为别名，对于一些基础用户来说，这是一个难以理解的事情——经验之谈。

2023-01-10 16:25 UTC, flycash requested changes
- TableOf(entity any, alias string)
- TableOf(entity any) 并且其它地方保持有别名就用别名，没别名就不用别名

这两个选择，你可以自由决策。

2023-01-11 16:13 UTC, merged

2023-01-11 16:14 UTC, flycash commented
我先合并了，我自己动手微调一下