WIP: feature ignore pk
gotomicro/eorm pull request #126
Opened 2023-01-06 17:01 UTC by Stone-afk

忽略主键，辅助方法 NonPKColumns(entity)[]string 目前只能是 Inserter 的方法，不然无法解析模型

2023-01-08 15:33 UTC, flycash commented on insert.go
> +func (i *Inserter[T]) NonPKColumns(entity any) (cols []string, err error) {
我其实不太想要这种解决方案，因为我觉得很丑，你有没有别的思路？

2023-01-08 15:33 UTC, flycash commented on insert.go
> +func (i *Inserter[T]) NonPKColumns(entity any) (cols []string, err error) {
至少，也没必要再传入一个 entity 了

2023-01-09 12:27 UTC, Stone-afk commented on insert.go
> +func (i *Inserter[T]) NonPKColumns(entity any) (cols []string, err error) {
我看issue里写的不是更倾向于这个方案? 还有一个方案就是设计一个对外函数和一个标记位，然后通过函数更改标记位的值，再根据标记为判断是否忽略主键

2023-01-10 03:32 UTC, flycash commented on insert.go
> +func (i *Inserter[T]) NonPKColumns(entity any) (cols []string, err error) {
我在 issue 里面说的是这种：
```go
func NonPKColumns(entity any) []string {

}
```

2023-01-10 03:34 UTC, flycash commented on insert.go
> +func (i *Inserter[T]) NonPKColumns(entity any) (cols []string, err error) {
不过这种方案难点在于，不好怎么在里面拿到 meta。定义在 Inserter 的话，就不如直接：
```go
func (i *Inserter) SkipPK() {

}
```

2023-01-10 06:06 UTC, Stone-afk commented on insert.go
> +func (i *Inserter[T]) NonPKColumns(entity any) (cols []string, err error) {
NonPKColumns(entity any) 方法 应该不可行，脱离了 build 根本拿不到 metaRegistry

2023-01-11 14:22 UTC, Stone-afk commented on insert.go
> +func (i *Inserter[T]) NonPKColumns(entity any) (cols []string, err error) {
尝试改为 SkipPK() 起码看起来顺眼多了 =。=

2023-01-13 06:29 UTC, flycash commented
等我再纠结纠结

2023-01-14 15:28 UTC, flycash requested changes

2023-01-14 15:28 UTC, flycash commented on insert.go
> +			if i.ignorePK && v.IsPrimaryKey {
如果用户指定了，就不要执行忽略了。或者用户又指定了，又想要忽略，可以考虑返回错误，因为我们也不知道怎么处理。

2023-01-14 15:28 UTC, flycash commented on insert_test.go
> +			name:     "ignore pk default",
在这边可以考虑提供一个测试用例，是复合主键的形态。

2023-01-14 15:47 UTC, Stone-afk commented on insert.go
> +			if i.ignorePK && v.IsPrimaryKey {
指定了就不忽略，这样因为用户自己指定列了，肯定知道自己想要返回什么

2023-01-14 15:48 UTC, Stone-afk commented on insert_test.go
> +			name:     "ignore pk default",
多个字段的主键？？

2023-01-16 05:45 UTC, flycash approved these changes

2023-01-16 05:46 UTC, merged