feat: 新增子查詢 & 單元測試
gotomicro/eorm pull request #131
Opened 2023-01-14 21:32 UTC by jwcrystal

支持 AsSubquery 輸入
   - 支持 FROM
   - 支持 WHERE，ALL，SOME，OR，EXIST
加入相對應的單元測試

2023-01-16 06:02 UTC, flycash requested changes

2023-01-16 07:45 UTC, flycash commented
合并一下最新代码

2023-01-16 12:40 UTC, jwcrystal commented on select.go
> +	if err := s.builder.buildColumn(column); err != nil {
雖然冗余了些，如果要維持一定風格，可以不刪？
如果只為了表示功能就是多餘的，可以刪？

2023-01-16 13:03 UTC, jwcrystal commented on select.go
> +	if err := s.builder.buildColumn(column); err != nil {
剛剛看了風格其實影響不大，刪了

2023-01-16 13:23 UTC, jwcrystal commented on select_test.go
> +func TestSelector_Subquery(t *testing.T) {
如果要區分不同表的話，一定要使用 FROM 的 表達式，不然無法構造出 AS 別名 的用法
這樣才可以表達類似 SELECT t1_1.id FROM t1 AS t1_1 WHERE t1_1.id > ALL (SELECT id FROM t2 ) AS t2_1

2023-01-16 13:27 UTC, jwcrystal commented on select_test.go
> +func TestSelector_Subquery(t *testing.T) {
再者就要考慮默認 SELECT  時候，是否需要帶上 “別名.字段”

2023-01-17 14:54 UTC, flycash requested changes
覆盖率不达标，应该就是一些比较关键的路径和方法没有测试到，你可以看 File Changed 来找到它们

2023-01-18 07:32 UTC, flycash approved these changes

2023-01-18 07:33 UTC, merged