wip 基于dns的slave发现的实现
gotomicro/eorm pull request #152
Opened 2023-02-15 12:50 UTC by juniaoshaonian

1. 针对dns的具体实现，我们需要提供吗
2. 关于容错，是在客户端做，还是在dns具体实现里面去做。

2023-02-17 07:33 UTC, flycash requested changes
居然没有开源的 DSN 解析库吗？

2023-02-17 07:33 UTC, flycash commented on internal/slaves/dns/dns.go
> +type DNS interface {
我觉得不需要这个抽象。你就直接去访问 DNS 服务器就可以了，也就是直接使用 net.Resolver，等后面有需要了再考虑抽象

2023-02-17 07:33 UTC, flycash commented on internal/slaves/dns/dns.go
> +func NewSlaves(dns DNS, interval time.Duration, dsn string, opts ...SlaveOption) (*Slaves, error) {
必传的就是一个 dsn，其它都是可选的

2023-02-17 07:36 UTC, flycash commented
1. 直接使用 net.Resolver;
2. 容错你是指解析 DNS 失败吗？你可以暴露一个回调，让用户处理；如果用户没有设置回调，默认的回调就是输出日志。但是目前来说这个不是很有必要，因为用户有特殊的需求，他们可以自己实现一个；
3. 暂时这个缓一缓，因为我也没想好怎么交互。后面我单独开一个 issue，设计一个通用的回调机制，即查询失败之后要通知 Slaves，可能需要在 Slaves 接口里面加一个方法；

2023-02-20 12:02 UTC, juniaoshaonian commented
明哥这种测试覆盖率咋提升，有些是其他接口的返回的错误，还有是那种option模式的

2023-02-20 14:54 UTC, flycash requested changes
这个 MySQLParse 我有一个疑问，dsn 不能用 net.Url 来表示吗？应该是 URI 来表示，我记得它就是一个普普通通的 uri？

2023-02-20 14:54 UTC, flycash commented on internal/slaves/dns/dns.go
> +type dns interface {
你定义一个私有的接口，里面是LookUpAddr 方法，而不是 listSlaves，便于测试

2023-02-20 14:54 UTC, flycash commented on internal/slaves/dns/dns.go
> +func withdns(d dns) SlaveOption {
这个你应该用不上，你直接在测试里面给 dns 赋值

2023-02-23 08:45 UTC, closed without merging