eorm, internal/mode, internal/valuer/reflect: 解决#81
gotomicro/eorm pull request #83
Opened 2022-08-19 02:34 UTC by longyue0521

1. mode.go 添加Index字段
2. mode_test.go     测试Index字段
3. reflect.go           使用自定义field方法(本质reflect.Value.Field)替换reflect.Value.FieldByName方法
4. unsafe_test.go   添加测试用例NullBoolPtr

2022-08-19 02:42 UTC, longyue0521 commented
https://github.com/gotomicro/eorm/discussions/82#discussion-4315205

2022-08-19 13:53 UTC, flycash commented
deepsource 里面有一个检查没过，你可以把 `field` 改成 `fieldByIdex`？或者你有更好的名字？

2022-08-19 13:55 UTC, flycash requested changes

2022-08-19 13:55 UTC, flycash commented on internal/valuer/reflect.go
> +func (r reflectValue) field(name string) reflect.Value {
返回值可以加一个 bool 值来标记究竟有没有这个 name。之前我这么写，是因为当时我不想再一次从元数据里面判断这个字段存在不存在，不过你这里已经自然判断了

2022-08-19 13:55 UTC, flycash commented on internal/valuer/reflect.go
> +func (r reflectValue) field(name string) reflect.Value {
提供一个这个`field` 方法和直接 `FieldByName` 的 benchmark 测试。虽然多了一个 map 操作不至于引入很多性能开销，但是我还是希望留下一个 benchmark 测试告诉后面的人为什么这么写

2022-08-20 03:07 UTC, longyue0521 commented on internal/valuer/reflect.go
> +func (r reflectValue) field(name string) reflect.Value {
1. Index属性是放在ColumnMeta中的,未来ColumnMeta中是否有记录数据库层面的索引相关元信息的需求?比如:这个列上是否有索引?唯一索引?索引名称?等. 本issues中我们想表示的是"当前ColumnMeta在TableMea‘s的Columns切片中的位置/序号",变量名不用Index改为seq(Sequence)或pos(position)会不会好点?
2. 我会把field改为fieldByIdex(加个注释解释一下)并增加一个bool返回值
3. benchmark我去学一下然后补上

2022-08-20 07:19 UTC, flycash commented on internal/valuer/reflect.go
> +func (r reflectValue) field(name string) reflect.Value {
有点道理，Index 可能会被误解。但是改成 seq 也不太好，因为在 Go 反射层面就叫 Index，而且在组合的情况下，其实它应该是一个 []int。
叫做 GoIndex 呢？或者 FieldIndex？

2022-08-21 09:08 UTC, longyue0521 commented on internal/valuer/reflect.go
> +func (r reflectValue) field(name string) reflect.Value {
FieldIndex吧与FieldMap对应

在组合情况下,

```go
type A struct {
    B string
    C C
    F int
}
type C struct {
    D int
    E string
}
```
E的ColumnMeta中FieldIndex = []int{1,1}

2022-08-21 09:21 UTC, flycash commented on internal/valuer/reflect.go
> +func (r reflectValue) field(name string) reflect.Value {
可以，就叫 FieldIndex 吧，你要是定义成数组的话（为了将来的组合），那么可以用复数形式

2022-08-22 16:14 UTC, flycash requested changes
- 把 field 的名字改一下，然后加一个 bool 作为返回值，== (reflect.Value) 还是比较丑的。
- 然后把 Index 改成 FieldIndex
- 然后在 .CHANGELOG 里面加一条记录，也就是这个 MR

2022-08-22 17:00 UTC, merged

2022-08-22 18:01 UTC, longyue0521 commented
不好意思,因为处理冲突不当导致本PR被关闭了, 请移步至#90