Delete的执行
gotomicro/eorm pull request #95
Opened 2022-09-20 08:46 UTC by TopWay2Hogwarts

sqlmock这么用不知是否正确，希望上课的时候把常见用法提一下，这个库给我整的有点糊涂。

集成测试写哪？

2022-09-20 13:04 UTC, flycash commented
集成测试在 internal 包里面的 integration 里面

2022-09-20 13:05 UTC, flycash commented on db.go
> +		session: db,
因为我们要坚持使用泛型，所以你可以把这个 Delete() 方法删掉，然后参考 NewSelector 或者 NewInserter 的形式，写一个新的创建的方法

2022-09-20 13:13 UTC, flycash requested changes

2022-09-20 13:13 UTC, flycash commented on delete.go
> +func (d *Deleter) ExecWithTx(ctx context.Context, delSession session) (sql.Result, error) {
不需要这个东西。主要是前面你加上 NewDeleter 之后，我们就可以传入一个 tx了。嘿嘿，算是我误导你了

2022-09-20 13:13 UTC, flycash commented on delete.go
> +	return newQuerier[Deleter](d.session, query).Exec(ctx)
把 Deleter 重构为泛型之后这里就不用传入 Deleter 作为类型参数了

2022-09-20 13:13 UTC, flycash commented on delete_test.go
> +		dbOrder   func(*DB) ([]sql.Result, []error)
这里只需要返回 sql.Result 和 error 就可以。在事务的那个测试用例里面，你可以在dbOrder 里面执行断言：
```go
			dbOrder: func(db *DB) (sql.Result, error) {
				tx, err:= db.BeginTx(context.Background(), &sql.TxOptions{})
                                require.NoError(err)
				result, retErr := db.Delete().From(&Product{}).Where(C("Id").EQ(1)).ExecWithTx(context.Background(), tx)
			
				err = tx.Commit()
				require.NoError(err)

				return result, retErr
			},
```

2022-09-20 13:13 UTC, flycash commented on delete_test.go
> +		dbOrder   func(*DB) ([]sql.Result, []error)
dbOrder 可以改名为 delete。因为你在里面就是为了执行 Delete。dbOrder 本身信息含量不高，看上去是看不出来这个方法准备做什么的

2022-09-20 13:13 UTC, flycash commented on delete_test.go
> +		dbOrder   func(*DB) ([]sql.Result, []error)
你的 sqlmock 用得很对！尤其是你注意到了在每一个测试里面单独创建 sqlmock DB，这样能有效避免不同的测试用例之间互相影响。

2022-09-22 03:02 UTC, TopWay2Hogwarts commented on db.go
> +		session: db,
我暂时倒是没删，我看 Update也是有相同问题，留给你一起删吧

2022-09-23 09:18 UTC, closed without merging