Delete() 完善
gotomicro/eorm pull request #96
Opened 2022-09-22 03:14 UTC by TopWay2Hogwarts

2022-09-22 03:21 UTC, TopWay2Hogwarts commented
之前申请合并成main分支了，新开一个，sorry...

2022-09-22 14:33 UTC, flycash requested changes

2022-09-22 14:33 UTC, flycash commented on db.go
> +	return &Deleter[DB]{
不是这样，是这样：
```go
NewDeleter[T any](sess session) *Deleter[T] {
}
```

那么如果用户使用的是：
```go
d := NewDeleter[User](db).Where(xxx)
```
他没有指定操作的表，那么我们就用 User 对应的表。

2022-09-22 14:33 UTC, flycash commented on delete.go
>  	d.meta, err = d.metaRegistry.Get(d.table)
如果用户没有传入这个 d.table，那么就用 T 对应的元数据。类似于：
```go
if d.table == nil {
    d.table = new(T)
}
```

2022-09-22 14:33 UTC, flycash commented on delete_test.go
> +				err = tx.Commit()
```go
				result, retErr := deleter.From(&TestProduct{}).Where(C("Id").EQ(1)).Exec(context.Background())
				

				err = tx.Commit()
                                require.NoError(t, err)
                                return result, retErr
```
然后在 mock 数据的时候正常 commit 就可以了。因为我们这里测试的是 Deleter 本身，所以我们一点都不关心 Commit 的问题。

即便要测试 commit，我们也是在事务里面测试的

2022-09-22 14:33 UTC, flycash commented on delete_test.go
> +			dbOrder: func(db *DB, t *testing.T) (sql.Result, error) {
把 dbOrder 改个名字，改成 delete。因为 dbOrder 看不出来是做什么的

2022-09-22 14:33 UTC, flycash commented on delete_test.go
> +			}
这边可以简化：
```go
assert.Equal(t, tc.wantVal, result)
```

2022-09-22 14:33 UTC, flycash commented on internal/integration/delete_test.go
> +			affected, err := res.RowsAffected()
这后面加一个 require.NoError(t, err)。确保你拿回 RowsAffected 的时候并没有遇到任何 error

2022-09-22 14:33 UTC, flycash commented on internal/integration/delete_test.go
> +	_, err := eorm.RawQuery[any](i.orm, "DELETE FROM `simple_struct`").Exec(context.Background())
我草，哈哈哈，我之前没有实现 Deleter 的时候才写成这个样子。你这里可以直接使用 Deleter 了。

2022-09-22 14:34 UTC, flycash commented
Format Go code 错误就是指你在本地运行一下 make check，这个命令会帮你格式化好代码，然后重新提交一下就可以了

2022-09-26 03:15 UTC, flycash commented
重新 rebase 过去最新代码

2022-09-27 06:06 UTC, flycash commented
@TopWay2Hogwarts 你这个还改吗？

2022-09-27 06:19 UTC, TopWay2Hogwarts commented
主要是卡在了返回结果比较的问题上，直接比较会有如下：
<img width="860" alt="image" src="https://user-images.githubusercontent.com/88173543/192447637-73babd46-fb74-420e-a16d-177f4d067c10.png">

尝试使用反射:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/88173543/192447738-6e758932-08ab-4157-907c-1a61e1e37a2a.png">

<img width="495" alt="image" src="https://user-images.githubusercontent.com/88173543/192447706-0db3307f-ec8e-49b6-9d32-6e4791fe4bc6.png">

2022-09-27 07:15 UTC, flycash commented
可以，我先合并了，然后我来改

2022-09-27 08:06 UTC, flycash commented
看起来还不太行，你就用原来的比较方式吧，后面我看看怎么优化这段测试代码 @TopWay2Hogwarts

2022-09-27 08:07 UTC, flycash commented
![image](https://user-images.githubusercontent.com/9923838/192470105-500cb315-d1cd-4b6c-a6c5-280df6b77cab.png)
这个例子改成 ExampleNewDeleter()

2022-09-27 08:08 UTC, flycash commented
deepsource 刚才是检测到我们删除了 DB 上的 Delete 方法，所以 ExampleDB_Delete 就不符合规范了。我们改成 ExampleNewDeleter 就没问题了

2022-10-08 11:46 UTC, merged