支持使用组合定义模型 #70
gotomicro/eorm pull request #99
Opened 2022-10-21 07:34 UTC by flyhigher139

完成组合，并添加了测试用例

2022-10-21 13:58 UTC, flycash requested changes
设计用例设计得不错。可以帮忙重构一下这个测试用例吗？就是在三个地方都写一遍字段的元数据有点崩溃，改成大概这样的一个方法：
```go
wantMeta: newTableMeta(tableName, columns)
```
columns 就是按照顺序放好的，然后内部把这个转成对应的两个 map，我觉得很能简化代码。

嘿嘿早期我这样测试，是因为早期我的元数据很简单，后面加多了之后我也没有改过来

2022-10-21 13:58 UTC, flycash commented on internal/model/model.go
> +			FieldIndexes:    append(fieldIndexes, i),
这里你能不能直接试一下就是用 structField.Index 我记得里面有一个字段大概叫做这个，然后是一个 []int，我有点忘了它是不是就能够直接拿到这个东西，也就是从组合最外面到达这个字段本身的各级的索引

2022-10-21 14:49 UTC, flyhigher139 commented
> 在三个地方都写一遍字段的元数据有点崩溃，改成大概这样的一个方法：
> 
> ```go
> wantMeta: newTableMeta(tableName, columns)
> ```
> 
> columns 就是按照顺序放好的，然后内部把这个转成对应的两个 map

收到～

> 这里你能不能直接试一下就是用 structField.Index 我记得里面有一个字段大概叫做这个，然后是一个 []int，我有点忘了它是不是就能够直接拿到这个东西，也就是从组合最外面到达这个字段本身的各级的索引

收到～

2022-10-21 16:15 UTC, flyhigher139 commented on internal/model/model.go
> +			FieldIndexes:    append(fieldIndexes, i),
试过了，只难道了本级的，上级的没拿到

2022-10-23 05:40 UTC, flycash commented on internal/model/model.go
> +			FieldIndexes:    append(fieldIndexes, i),
这里你试了我说的直接拿整个 index 的那个 API 吗？可以用吗？

2022-10-23 10:54 UTC, flyhigher139 commented on internal/model/model.go
> +			FieldIndexes:    append(fieldIndexes, i),
是`structField.Index`么？返回结果的切片，就一个元素，没拿到父级的索引

2022-10-24 02:43 UTC, flycash approved these changes

2022-10-24 02:43 UTC, merged

2022-10-24 02:44 UTC, flycash commented
@flyhigher139 接下来，你需要在构造 SQL 和执行查询的那些地方都加一些测试用例。按照道理来说，应该能够直接运行，毕竟我们只依赖于元数据。

然后你确认一下那个 parents 字段，在使用 index 之后我觉得那个可能用不上了

2022-10-24 05:37 UTC, flyhigher139 commented
> @flyhigher139 接下来，你需要在构造 SQL 和执行查询的那些地方都加一些测试用例。按照道理来说，应该能够直接运行，毕竟我们只依赖于元数据。
> 
> 然后你确认一下那个 parents 字段，在使用 index 之后我觉得那个可能用不上了

好的～